source 'https://cdn.cocoapods.org/'

platform :ios, "11.0"
use_modular_headers!

target 'TestingProject_Example' do
  pod 'TestingProject', :path => '../'
  
  pod 'IGListKit', '4.0.0'
  pod 'InnerPod', :path => '../../InnerPod'
end
